In [4]:
"""traditional method in python to find the sum of two lists"""
list_1=[1,3,5,6]
list_2=[8,4,5,6]
sum=list_1+list_2 
print(sum)   #it will combine the two lists instead of getting the sum


[1, 3, 5, 6, 8, 4, 5, 6]


In [5]:
list_3=[]
for i,j in zip(list_1,list_2):#The zip() function takes iterables (can be zero or more), aggregates them in a tuple, and returns it.
    list_3.append(i+j)
print(list_3)

[9, 7, 10, 12]


## NumPy

In [6]:
import numpy as np

In [7]:
np.array(list_1) #convert the list into an array

array([1, 3, 5, 6])

In [11]:
arr1=np.array(list_1) #stored it in a variable

In [12]:
arr1

array([1, 3, 5, 6])

In [13]:
arr2=np.array(list_2)

In [14]:
arr2

array([8, 4, 5, 6])

In [15]:
sum1= arr1+arr2

In [16]:
sum1 #will add both arrays

array([ 9,  7, 10, 12])

In [17]:
%whos #to list varibles

Variable   Type       Data/Info
-------------------------------
arr1       ndarray    4: 4 elems, type `int32`, 16 bytes
arr2       ndarray    4: 4 elems, type `int32`, 16 bytes
i          int        6
j          int        6
list_1     list       n=4
list_2     list       n=4
list_3     list       n=4
np         module     <module 'numpy' from 'E:\<...>ges\\numpy\\__init__.py'>
sum        list       n=8
sum1       ndarray    4: 4 elems, type `int32`, 16 bytes


In [18]:
data2 = [[1,2,5],[4,8,3]]

In [19]:
data2

[[1, 2, 5], [4, 8, 3]]

In [22]:
arr_data=np.array(data2)
arr_data

array([[1, 2, 5],
       [4, 8, 3]])

In [23]:
arr_data.ndim #to check the dimension of the array

2

In [24]:
arr_data.dtype #will check the data type of the array

dtype('int32')

In [26]:
arr_data.shape #will give the shape of the array, number of raws and number of coloumns

(2, 3)

In [29]:
arr_data1 = np.array(arr_data,dtype=float) #to change the type to float
arr_data1

array([[1., 2., 5.],
       [4., 8., 3.]])

In [31]:
arr3=np.array(['1','2','5'])
arr3.dtype #U1 stands for unicode(string data type)

dtype('<U1')

In [33]:
arr4= np.array(arr3,dtype=int)
print(arr4)
arr4.dtype

[1 2 5]


dtype('int32')

In [35]:
list(range(7)) #normal method to print 0-6 values

[0, 1, 2, 3, 4, 5, 6]

In [36]:
np.arange(7) #in numpy we use arange() to output the values

array([0, 1, 2, 3, 4, 5, 6])

In [41]:
arr6=np.arange(4,20,2) #increment 2 
arr6

array([ 4,  6,  8, 10, 12, 14, 16, 18])

In [43]:
arr7=arr6.reshape(4,2) #to reshape the dimension of the array
arr7

array([[ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [45]:
arr8=np.linspace(1,30,5) #will randomally divide 1 to 30 values in 5 parts
arr8

array([ 1.  ,  8.25, 15.5 , 22.75, 30.  ])

In [46]:
arr9=np.linspace(1,12,4)
arr9

array([ 1.        ,  4.66666667,  8.33333333, 12.        ])

In [47]:
arr=np.arange(5,20)
arr

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [48]:
arr[5:12]

array([10, 11, 12, 13, 14, 15, 16])

In [49]:
arr[5]

10

In [50]:
arr[12]

17

In [52]:
arr[5:] #print values from 5th index upto last

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [53]:
arr[:5] #from first index upto 4th index

array([5, 6, 7, 8, 9])

In [54]:
arr[1,3,5]

IndexError: too many indices for array: array is 1-dimensional, but 3 were indexed

In [56]:
arr[[1,2,5]]

array([ 6,  7, 10])

In [70]:
arr_2=np.array([[7,5,-8],[-5,2,-3],])
arr_2=arr_2.reshape(3,2)
print(arr_2)
arr_2.ndim


[[ 7  5]
 [-8 -5]
 [ 2 -3]]


2

In [72]:
arr_2[1] #will output only the raw in the index 1

array([-8, -5])

In [74]:
arr_2[1,0] #will takeout the specific value 

-8

In [75]:
arr_2[[1,0]] #to take out multiple raws

array([[-8, -5],
       [ 7,  5]])

In [77]:
arr_2[:,1]

array([ 5, -5, -3])

In [80]:
arr_3=np.arange(10,82,2)
arr_3

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76,
       78, 80])

In [81]:
len(arr_3) #show how many elements in the array

36

In [85]:
arr_4=arr_3.reshape(6,6)
arr_4

array([[10, 12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30, 32],
       [34, 36, 38, 40, 42, 44],
       [46, 48, 50, 52, 54, 56],
       [58, 60, 62, 64, 66, 68],
       [70, 72, 74, 76, 78, 80]])

In [86]:
arr_4[:,[0,2]]

array([[10, 14],
       [22, 26],
       [34, 38],
       [46, 50],
       [58, 62],
       [70, 74]])

In [88]:
arr_4[:,0:3]

array([[10, 12, 14],
       [22, 24, 26],
       [34, 36, 38],
       [46, 48, 50],
       [58, 60, 62],
       [70, 72, 74]])

In [93]:
arr_4[:2,0:3]

array([[10, 12, 14],
       [22, 24, 26]])

In [96]:
arr_5=np.array([3,4,5,6])
arr_5

array([3, 4, 5, 6])

In [97]:
np.sum(arr_5) #to find the sum of all elements inside this array

18

In [99]:
arr_5.sum() #another method to find the sum

18

In [100]:
arr_5.mean() #to find the mean

4.5

In [101]:
np.mean(arr_5) #another method to find the mean

4.5

In [103]:
np.median(arr_5) #to find the median

4.5

In [104]:
arr_5

array([3, 4, 5, 6])

In [106]:
arr_5 = arr_5.reshape(2,2)
arr_5

array([[3, 4],
       [5, 6]])

In [107]:
arr_5.sum()

18

In [114]:
arr_5.sum(axis=0) #give the sum with respect to the y-axis (column wise)

array([ 8, 10])

In [116]:
arr_5.sum(axis=1) #give the sum with respect to x-axis (raw wise)

array([ 7, 11])

In [117]:
arr_4

array([[10, 12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30, 32],
       [34, 36, 38, 40, 42, 44],
       [46, 48, 50, 52, 54, 56],
       [58, 60, 62, 64, 66, 68],
       [70, 72, 74, 76, 78, 80]])

In [118]:
arr_4+5  #scalar operation. Adds this number with every numbers inside the array

array([[15, 17, 19, 21, 23, 25],
       [27, 29, 31, 33, 35, 37],
       [39, 41, 43, 45, 47, 49],
       [51, 53, 55, 57, 59, 61],
       [63, 65, 67, 69, 71, 73],
       [75, 77, 79, 81, 83, 85]])

In [119]:
arr_4-5

array([[ 5,  7,  9, 11, 13, 15],
       [17, 19, 21, 23, 25, 27],
       [29, 31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49, 51],
       [53, 55, 57, 59, 61, 63],
       [65, 67, 69, 71, 73, 75]])

In [120]:
arr_4*5

array([[ 50,  60,  70,  80,  90, 100],
       [110, 120, 130, 140, 150, 160],
       [170, 180, 190, 200, 210, 220],
       [230, 240, 250, 260, 270, 280],
       [290, 300, 310, 320, 330, 340],
       [350, 360, 370, 380, 390, 400]])

In [122]:
arr_4[5] = -9
arr_4

array([[10, 12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30, 32],
       [34, 36, 38, 40, 42, 44],
       [46, 48, 50, 52, 54, 56],
       [58, 60, 62, 64, 66, 68],
       [-9, -9, -9, -9, -9, -9]])

In [123]:
np.abs(arr_4) #absolute function will do changing negative value to positive value inside the array

array([[10, 12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30, 32],
       [34, 36, 38, 40, 42, 44],
       [46, 48, 50, 52, 54, 56],
       [58, 60, 62, 64, 66, 68],
       [ 9,  9,  9,  9,  9,  9]])

In [125]:
arr_4=np.abs(arr_4)
arr_4

array([[10, 12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30, 32],
       [34, 36, 38, 40, 42, 44],
       [46, 48, 50, 52, 54, 56],
       [58, 60, 62, 64, 66, 68],
       [ 9,  9,  9,  9,  9,  9]])

In [126]:
np.sqrt(arr_4) #will take the squreroot of array

array([[3.16227766, 3.46410162, 3.74165739, 4.        , 4.24264069,
        4.47213595],
       [4.69041576, 4.89897949, 5.09901951, 5.29150262, 5.47722558,
        5.65685425],
       [5.83095189, 6.        , 6.164414  , 6.32455532, 6.4807407 ,
        6.63324958],
       [6.78232998, 6.92820323, 7.07106781, 7.21110255, 7.34846923,
        7.48331477],
       [7.61577311, 7.74596669, 7.87400787, 8.        , 8.1240384 ,
        8.24621125],
       [3.        , 3.        , 3.        , 3.        , 3.        ,
        3.        ]])

In [127]:
type(arr_4)

numpy.ndarray

In [130]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [131]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [135]:
np.eye(5,5) #all the diagonal elements are zero

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [149]:
A= np.arange(0,30).reshape(3,10)
B= np.arange(0,50).reshape(10,5)

In [150]:
A

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [151]:
B

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [152]:
A.dot(B) #matrix multiplication. Number of raws in the first matrix have to equal to the number of columns in the second matrix

array([[1425, 1470, 1515, 1560, 1605],
       [3675, 3820, 3965, 4110, 4255],
       [5925, 6170, 6415, 6660, 6905]])