In [4]:
"""traditional method in python to find the sum of two lists"""
list_1=[1,3,5,6]
list_2=[8,4,5,6]
sum=list_1+list_2 
print(sum)   #it will combine the two lists instead of getting the sum


[1, 3, 5, 6, 8, 4, 5, 6]


In [5]:
list_3=[]
for i,j in zip(list_1,list_2):#The zip() function takes iterables (can be zero or more), aggregates them in a tuple, and returns it.
    list_3.append(i+j)
print(list_3)

[9, 7, 10, 12]


## NumPy

In [6]:
import numpy as np

In [7]:
np.array(list_1) #convert the list into an array

array([1, 3, 5, 6])

In [11]:
arr1=np.array(list_1) #stored it in a variable

In [12]:
arr1

array([1, 3, 5, 6])

In [13]:
arr2=np.array(list_2)

In [14]:
arr2

array([8, 4, 5, 6])

In [15]:
sum1= arr1+arr2

In [16]:
sum1 #will add both arrays

array([ 9,  7, 10, 12])

In [17]:
%whos #to list varibles

Variable   Type       Data/Info
-------------------------------
arr1       ndarray    4: 4 elems, type `int32`, 16 bytes
arr2       ndarray    4: 4 elems, type `int32`, 16 bytes
i          int        6
j          int        6
list_1     list       n=4
list_2     list       n=4
list_3     list       n=4
np         module     <module 'numpy' from 'E:\<...>ges\\numpy\\__init__.py'>
sum        list       n=8
sum1       ndarray    4: 4 elems, type `int32`, 16 bytes


In [18]:
data2 = [[1,2,5],[4,8,3]]

In [19]:
data2

[[1, 2, 5], [4, 8, 3]]

In [22]:
arr_data=np.array(data2)
arr_data

array([[1, 2, 5],
       [4, 8, 3]])

In [23]:
arr_data.ndim #to check the dimension of the array

2

In [24]:
arr_data.dtype #will check the data type of the array

dtype('int32')

In [26]:
arr_data.shape #will give the shape of the array, number of raws and number of coloumns

(2, 3)

In [29]:
arr_data1 = np.array(arr_data,dtype=float) #to change the type to float
arr_data1

array([[1., 2., 5.],
       [4., 8., 3.]])

In [31]:
arr3=np.array(['1','2','5'])
arr3.dtype #U1 stands for unicode(string data type)

dtype('<U1')

In [33]:
arr4= np.array(arr3,dtype=int)
print(arr4)
arr4.dtype

[1 2 5]


dtype('int32')

In [35]:
list(range(7)) #normal method to print 0-6 values

[0, 1, 2, 3, 4, 5, 6]

In [36]:
np.arange(7) #in numpy we use arange() to output the values

array([0, 1, 2, 3, 4, 5, 6])

In [41]:
arr6=np.arange(4,20,2) #increment 2 
arr6

array([ 4,  6,  8, 10, 12, 14, 16, 18])

In [43]:
arr7=arr6.reshape(4,2) #to reshape the dimension of the array
arr7

array([[ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [45]:
arr8=np.linspace(1,30,5) #will randomally divide 1 to 30 values in 5 parts
arr8

array([ 1.  ,  8.25, 15.5 , 22.75, 30.  ])

In [46]:
arr9=np.linspace(1,12,4)
arr9

array([ 1.        ,  4.66666667,  8.33333333, 12.        ])